### ISSUE TITLE
OAuth2client >= 4.0.0 file_cache warning

### ISSUE THREAD

**Issue by rdoursenaud** [GoogleCloudPlatformTraining/cpo201-Google-Cloud-SQL-Admin-API#1]
Running `sqladmin.py` with the latest oauth2client installed results in the following warning:
```
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
```

**Comment by tomgcp** [comment]
Investigating.
